In [1]:
# show → code input visible by default
# hide-output → output hidden by default
# show hide-output → both (can combine on one line)

import pandas as pd
#from google.cloud import bigquery
from common_lib.sql import BigQueryConnector
from common_lib.export import export_notebook_html
import datetime as dt
import plotly.express as px

In [2]:
refresh_data = True

In [3]:
query_location = './sql/int_user_gems_flows.sql'

# Pulled in monthly chunks to avoid BQ's "Response too large to return" error on the
# full-year select * (likely a Storage API fallback to the size-capped tabledata.list path).
month_starts = pd.date_range('2022-07-01', '2024-12-01', freq='MS')
month_ranges = [(d.strftime('%Y-%m-%d'), (d + pd.offsets.MonthEnd(0)).strftime('%Y-%m-%d')) for d in month_starts]

bqc = BigQueryConnector()
for start_date, end_date in month_ranges:
    bqc.print_cost_estimate(query=query_location, is_path=True, query_parameters={'start_date': start_date, 'end_date': end_date})

This query will process 5.72 GB when run.
Estimated query cost: $0.04
This query will process 5.54 GB when run.
Estimated query cost: $0.04
This query will process 5.36 GB when run.
Estimated query cost: $0.04
This query will process 6.02 GB when run.
Estimated query cost: $0.04
This query will process 6.42 GB when run.
Estimated query cost: $0.04
This query will process 6.98 GB when run.
Estimated query cost: $0.05
This query will process 7.74 GB when run.
Estimated query cost: $0.05
This query will process 7.60 GB when run.
Estimated query cost: $0.05
This query will process 9.42 GB when run.
Estimated query cost: $0.06
This query will process 9.79 GB when run.
Estimated query cost: $0.07
This query will process 8.20 GB when run.
Estimated query cost: $0.06
This query will process 8.42 GB when run.
Estimated query cost: $0.06
This query will process 8.25 GB when run.
Estimated query cost: $0.06
This query will process 7.89 GB when run.
Estimated query cost: $0.05
This query will process 8.46 GB when run.
Estimated query cost: $0.06
This query will process 9.55 GB when run.
Estimated query cost: $0.06
This query will process 8.80 GB when run.
Estimated query cost: $0.06
This query will process 9.67 GB when run.
Estimated query cost: $0.06
This query will process 9.69 GB when run.
Estimated query cost: $0.07
This query will process 10.05 GB when run.
Estimated query cost: $0.07
This query will process 9.72 GB when run.
Estimated query cost: $0.07
This query will process 8.46 GB when run.
Estimated query cost: $0.06
This query will process 8.54 GB when run.
Estimated query cost: $0.06
This query will process 9.02 GB when run.
Estimated query cost: $0.06
This query will process 7.98 GB when run.
Estimated query cost: $0.05
This query will process 7.86 GB when run.
Estimated query cost: $0.05
This query will process 7.86 GB when run.
Estimated query cost: $0.05
This query will process 7.10 GB when run.
Estimated query cost: $0.05
This query will process 7.14 GB when run.
Estimated query cost: $0.05
This query will process 6.06 GB when run.
Estimated query cost: $0.04

In [4]:
month_pkl_paths = [f'./data/int_user_gems_flows_data_{start_date[:7]}.pkl' for start_date, _ in month_ranges]

if refresh_data:
    for (start_date, end_date), pkl_path in zip(month_ranges, month_pkl_paths):
        df_month = bqc.get(query='./sql/int_user_gems_flows.sql', is_path=True,
                            query_parameters={'start_date': start_date, 'end_date': end_date})
        df_month.to_pickle(pkl_path)
        del df_month

KeyboardInterrupt:

In [ ]:
for pkl_path in month_pkl_paths:
    df_month = pd.read_pickle(pkl_path)
    df_month.to_csv(pkl_path.replace('.pkl', '.csv.zip'), index=False)
    del df_month

In [ ]:
test

In [ ]:
query_location = './sql/km_trk_user_iap_revenue_monthly.sql'
parameters = {
}

bqc = BigQueryConnector()
cost_info = bqc.print_cost_estimate(query=query_location, is_path=True, query_parameters=parameters)

This query will process 210.7 MB when run.
Estimated query cost: $0.00

In [ ]:
km_trk_user_iap_revenue_monthly = pd.DataFrame()

if refresh_data:
    km_trk_user_iap_revenue_monthly = bqc.get(query='./sql/km_trk_user_iap_revenue_monthly.sql', is_path=True, query_parameters=parameters)
    km_trk_user_iap_revenue_monthly.to_pickle('./data/km_trk_user_iap_revenue_monthly_data.pkl')
else:
    km_trk_user_iap_revenue_monthly = pd.read_pickle('./data/km_trk_user_iap_revenue_monthly_data.pkl')

In [ ]:
km_trk_user_iap_revenue_monthly.to_csv('./data/km_trk_user_iap_revenue_monthly_data.csv', index=False)

In [ ]:
km_trk_user_iap_revenue_monthly

,user_id,month_start_dt,max_active_dt,min_purchase_dt,bool_is_payer,total_iap_revenue_usd,total_iap_gems_only_revenue_usd,total_iap_non_gem_revenue_usd
0,FBAFD707E8910B7C,2025-07-01,2025-07-01,NaT,<NA>,NaN,NaN,NaN
1,FAFDC01FD9221B96,2025-07-01,2025-07-01,NaT,<NA>,NaN,NaN,NaN
2,FD38290FD318EDD3,2025-07-01,2025-07-01,NaT,<NA>,NaN,NaN,NaN
3,FF5D9D92B2F34AEA,2025-07-01,2025-07-01,NaT,<NA>,NaN,NaN,NaN
4,FAF3877EE1299E3C,2025-07-01,2025-07-01,NaT,<NA>,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
4921813,34D69E3B91CFA7D0,2025-08-01,2025-08-31,2025-08-01,1,1147.010000,59.940000,1087.07000
4921814,3D51898CD12E8DBA,2025-08-01,2025-08-31,2025-08-01,1,1183.720000,204.700000,979.02000
4921815,53BC163D94385509,2025-08-01,2025-08-31,2025-08-01,1,1392.671352,686.694212,705.97714
4921816,1CDE20EE5F660449,2025-08-01,2025-08-31,2025-08-01,1,1452.040000,339.950000,1112.09000
4921817,8C154CB90F4DE5B6,2025-08-01,2025-08-31,2025-08-01,1,1753.390000,19.990000,1733.40000

In [ ]:
query_location = './sql/km_users_to_exclude.sql'
parameters = {
}

bqc = BigQueryConnector()
cost_info = bqc.print_cost_estimate(query=query_location, is_path=True, query_parameters=parameters)

This query will process 5.0 MB when run.
Estimated query cost: $0.00

In [ ]:
km_users_to_exclude = pd.DataFrame()

if refresh_data:
    km_users_to_exclude = bqc.get(query='./sql/km_users_to_exclude.sql', is_path=True, query_parameters=parameters)
    km_users_to_exclude.to_pickle('./data/km_users_to_exclude_data.pkl')
else:
    km_users_to_exclude = pd.read_pickle('./data/km_users_to_exclude_data.pkl')

In [ ]:
km_users_to_exclude.to_csv('./data/km_users_to_exclude_data.csv', index=False)

In [ ]:
km_users_to_exclude

,userid,bool_user_to_exclude,min_exclude_date,max_exclude_date,had_energy_recharge_bug,hacked_free_gems_earned_energy,hacked_free_gems_earned_callacustomer,hacked_free_gems_earned_heartshop_storage,qa_tester_gifted_gems,spent_more_10K_free_gems_one_day,earned_more_1K_free_gems_one_day,gems_balance_200K_plus,is_tester
0,7EA90E17C5799AB2,1,2026-07-14,2026-07-14,0,0,0,0,0,0,0,1,0
1,F2879196FACC5D7B,1,2026-07-14,2026-07-14,0,0,0,0,0,0,0,1,0
2,DE028591A4B3FB06,1,2026-07-14,2026-07-27,0,0,0,0,0,1,0,1,0
3,FAFE9C7AE2B5C40F,1,2026-07-14,2026-07-25,0,0,0,0,0,1,0,1,0
4,1A4DD2A5E793FAE,1,2024-07-10,2024-07-14,0,0,0,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45966,466F4D18CF42B,1,2022-11-26,2023-03-27,0,0,0,0,0,1,0,1,0
45967,3A3077338E3DFC31,1,2022-11-26,2023-03-27,0,0,0,0,0,1,0,1,0
45968,DA0A492E66504620,1,2022-11-26,2023-05-10,0,0,0,0,0,1,0,1,0
45969,21700E27051E22DD,1,2022-11-26,2023-11-03,0,0,0,0,0,1,0,1,0
45970,FAE20A7ED741B024,1,2022-11-26,2023-11-26,0,0,0,0,0,1,0,1,0